# Site settings
title: NEWS⓵
description: "AGORA 合众社"
baseurl: "/news1"
url: "https://theagora.github.io"
logo: "/assets/img/logo.png"
copyright: "Agora Community"

# Plugin settings
plugins:
  - jemoji

# Navbar settings
nav_exclude:
  - pages/index.md

# Collections
collections_dir: _collections
collections:
  blog0:
    output: true
    permalink: /blog0/:name
  news0:
    output: true
    permalink: /news0/:name
  pen0:
    output: true
    permalink: /pen0/:name

# Social networks
social:
  - title: twitter
    url: https://twitter.com/agoradao
  - title: reddit
    url: https://reddit.com/u/agoradao
  - title: slack
    url: https://agora-republic.slack.com
  - title: github
    url: https://github.com/agorahub

# Build settings
markdown: kramdown
exclude:
  - .*
